import { InnerChainUniqueId } from "../../../types/ChainUniqueId";
import { CoinType } from "../../../types/CoinType";
import { ExplorerLanguages } from "../../../types/ExplorerLanguages";
import { EthConfig } from "../types/EthConfig";

export const ETH_CHAIN_CONFIGS: { [key in string]: EthConfig } = {
  [InnerChainUniqueId.ETHEREUM]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.ETHEREUM,
    logo: require("@/assets/images/chains/eth.webp"),
    chainId: "1",
    chainName: "Ethereum",
    nativeCurrency: {
      name: "ETH",
      decimals: 18,
      symbol: "ETH",
      icon: require("@/assets/images/tokens/eth_token.webp"),
    },
    rpcList: [
      "https://eth-web3.foxnb.net/rpc",
      "https://eth-mainnet.alchemyapi.io/v2/QIC4cXI_Bia9RFYKpSS54mhi4V3x17C_",
      "https://cloudflare-eth.com",
      "https://rpc.ankr.com/eth",
      "https://api.edennetwork.io/v1/rpc",
      "https://ethereum.blockpi.network/v1/rpc/public",
    ],
    blockscoutApiList: ["https://eth.blockscout.com/api"],
    blockbookApiList: [
      "https://eth1.trezor.io",
      "https://eth-blockbook.foxnb.net",
      "https://eth2.trezor.io",
      "https://ethblockexplorer.org",
    ],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://etherscan.io",
      [ExplorerLanguages.ZH]: "https://etherscan.io",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/token/{token}?a={addr}",
    },
    nft: {
      supportResync: true,
    },
    nftMarkets: [
      {
        name: "OpenSea",
        baseUrl: "https://opensea.io",
        collectionPath: "/assets/ethereum/{addr}",
        itemPath: "/assets/ethereum/{addr}/{id}",
      },
      {
        name: "LooksRare",
        baseUrl: "https://looksrare.org",
        collectionPath: "/collections/{addr}",
        itemPath: "/collections/{addr}/{id}",
      },
      {
        name: "X2Y2",
        baseUrl: "https://x2y2.io",
        collectionPath: "",
        itemPath: "/eth/{addr}/{id}",
      },
      {
        name: "Blur",
        baseUrl: "https://blur.io",
        collectionPath: "/collection/{addr}",
        itemPath: "/asset/{addr}/{id}",
      },
    ],
    minGasLimits: [
      {
        contract: "0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84", // stETH
        functionHash: "0xa9059cbb", // transfer
        gasLimit: 130000,
      },
      {
        functionHash: "0xa9059cbb", // transfer
        gasLimit: 52000,
      },
    ],
  },
  [InnerChainUniqueId.BNB]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.BNB,
    logo: require("@/assets/images/chains/bnb.webp"),
    chainId: "56",
    chainName: "BNB Chain",
    nativeCurrency: {
      name: "Binance Chain Native Token",
      decimals: 18,
      symbol: "BNB",
    },
    rpcList: [
      "https://bsc-dataseed1.binance.org",
      "https://bsc-dataseed1.defibit.io",
      "https://bsc.publicnode.com",
      "https://bsc-dataseed1.ninicoin.io",
      "https://bsc-dataseed2.binance.org",
      "https://bsc-dataseed2.defibit.io",
      "https://bsc-mainnet.gateway.pokt.network/v1/lb/6136201a7bad1500343e248d",
      "https://bsc-dataseed2.ninicoin.io",
      "https://bsc-dataseed3.binance.org",
      "https://bsc-dataseed3.defibit.io",
      "https://bsc-dataseed3.ninicoin.io",
      "https://bsc-dataseed4.binance.org",
      "https://bsc-dataseed4.defibit.io",
      "https://bsc-dataseed4.ninicoin.io",
    ],
    blockbookApiList: [
      "https://bsc-blockbook.foxnb.net",
      "https://bsc.blockbook.chains.klever.io",
      "https://bsc-blockbook2.foxnb.net",
    ],
    blockscoutApiList: ["https://api.bscscan.com/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://bscscan.com",
      [ExplorerLanguages.ZH]: "https://bscscan.com",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/token/{token}?a={addr}",
    },
    nft: {
      supportResync: true,
    },
    nftMarkets: [
      {
        name: "OpenSea",
        baseUrl: "https://opensea.io",
        collectionPath: "/assets/bsc/{addr}",
        itemPath: "/assets/bsc/{addr}/{id}",
      },
      {
        name: "Element",
        baseUrl: "https://element.market",
        collectionPath: "/assets/bsc/{addr}",
        itemPath: "/assets/bsc/{addr}/{id}",
      },
    ],
    minGasLimits: [
      {
        contract: "0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56", // BUSD
        functionHash: "0xa9059cbb", // transfer
        gasLimit: 59100,
      },
      {
        contract: "0x55d398326f99059ff775485246999027b3197955", // USDT
        functionHash: "0xa9059cbb", // transfer
        gasLimit: 53000,
      },
      {
        functionHash: "0xa9059cbb", // transfer
        gasLimit: 52000,
      },
    ],
  },
  [InnerChainUniqueId.ETC]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.ETC,
    logo: require("@/assets/images/chains/etc.webp"),
    chainId: "61",
    chainName: "Ethereum Classic",
    nativeCurrency: {
      name: "Ethereum Classic Ether",
      decimals: 18,
      symbol: "ETC",
    },
    rpcList: [
      "https://www.ethercluster.com/etc",
      "https://geth-at.etc-network.info",
      "https://etc.etcdesktop.com",
      "https://etc.mytokenpocket.vip",
    ],
    blockscoutApiList: ["https://blockscout.com/etc/mainnet/api"],
    blockbookApiList: ["https://etc1.trezor.io", "https://etc2.trezor.io"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://blockscout.com/etc/mainnet/",
      [ExplorerLanguages.ZH]: "https://blockscout.com/etc/mainnet/",
    },
    explorerPaths: {
      tx: "tx/{txid}",
      address: "address/{addr}",
      token: "address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
  },
  [InnerChainUniqueId.ARBITRUM]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.ARBITRUM,
    logo: require("@/assets/images/chains/arbitrum.webp"),
    chainId: "42161",
    chainName: "Arbitrum One",
    nativeCurrency: {
      name: "Ether",
      decimals: 18,
      symbol: "ARETH",
      icon: require("@/assets/images/tokens/eth_token.webp"),
    },
    rpcList: [
      "https://arb1.arbitrum.io/rpc",
      "https://arb-mainnet.g.alchemy.com/v2/d4xxq0jVRxknPi5fZbq9uZ38_PIUWSyq",
      "https://rpc.ankr.com/arbitrum",
      "https://endpoints.omniatech.io/v1/arbitrum/one/public",
      "https://arbitrum.blockpi.network/v1/rpc/public",
      "https://arbitrum-one.public.blastapi.io",
      "https://arbitrum-one.blastapi.io/1279251a-ca2d-4491-bb80-849a5b0c77fe",
    ],
    blockscoutApiList: ["https://api.arbiscan.io/api"],
    nft: {
      supportResync: true,
    },
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://arbiscan.io",
      [ExplorerLanguages.ZH]: "https://arbiscan.io",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/token/{token}?a={addr}",
    },
    nftMarkets: [
      {
        name: "OpenSea",
        baseUrl: "https://opensea.io",
        collectionPath: "/assets/arbitrum/{addr}",
        itemPath: "/assets/arbitrum/{addr}/{id}",
      },
      {
        name: "Trove",
        baseUrl: "https://trove.treasure.lol",
        collectionPath: "/collection/{addr}",
        itemPath: "/collection/{addr}/{id}",
      },
      {
        name: "tofuNFT",
        baseUrl: "https://tofunft.com",
        collectionPath: "",
        itemPath: "/nft/arbi/{addr}/{id}",
      },
    ],
    minGasLimits: [
      {
        functionHash: "0xa9059cbb", // transfer
        gasLimit: 52000,
      },
    ],
  },
  [InnerChainUniqueId.ARBITRUM_NOVA]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.ARBITRUM_NOVA,
    logo: require("@/assets/images/chains/nova.webp"),
    chainId: "42170",
    chainName: "Arbitrum Nova",
    nativeCurrency: {
      name: "Ether",
      decimals: 18,
      symbol: "ETH",
      icon: require("@/assets/images/tokens/eth_token.webp"),
    },
    rpcList: [
      "https://nova.arbitrum.io/rpc",
      "https://arbitrum-nova.public.blastapi.io",
    ],
    blockscoutApiList: ["https://nova-explorer.arbitrum.io/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://nova-explorer.arbitrum.io",
      [ExplorerLanguages.ZH]: "https://nova-explorer.arbitrum.io",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
  },
  [InnerChainUniqueId.NEAR]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.NEAR,
    logo: require("@/assets/images/chains/aurora.webp"),
    chainId: "1313161554",
    chainName: "Aurora",
    nativeCurrency: {
      name: "Ether",
      decimals: 18,
      symbol: "aETH",
      icon: require("@/assets/images/tokens/eth_token.webp"),
    },
    rpcList: [
      "https://mainnet.aurora.dev",
      "https://aurora-mainnet.infura.io/v3/6b851498cebb4893b436e986cf1f5458",
      "https://endpoints.omniatech.io/v1/aurora/mainnet/public",
    ],
    blockscoutApiList: ["https://explorer.mainnet.aurora.dev/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://explorer.mainnet.aurora.dev",
      [ExplorerLanguages.ZH]: "https://explorer.mainnet.aurora.dev",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
  },
  [InnerChainUniqueId.AVAX]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.AVAX,
    logo: require("@/assets/images/chains/avax.webp"),
    chainId: "43114",
    chainName: "Avalanche C-Chain",
    nativeCurrency: {
      name: "Avalanche",
      decimals: 18,
      symbol: "AVAX",
    },
    rpcList: [
      "https://api.avax.network/ext/bc/C/rpc",
      "https://rpc.ankr.com/avalanche",
      "https://avax-mainnet.gateway.pokt.network/v1/lb/62738233ea1b320039c49a6c",
      "https://avalanche-mainnet.infura.io/v3/6b851498cebb4893b436e986cf1f5458",
      "https://avalanche-c-chain.publicnode.com",
    ],
    blockscoutApiList: ["https://api.snowtrace.io/api"],
    nft: {
      supportResync: true,
    },
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://snowtrace.io",
      [ExplorerLanguages.ZH]: "https://snowtrace.io",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/token/{token}?a={addr}",
    },
    nftMarkets: [
      {
        name: "OpenSea",
        baseUrl: "https://opensea.io",
        collectionPath: "/assets/avalanche/{addr}",
        itemPath: "/assets/avalanche/{addr}/{id}",
      },
      {
        name: "tofuNFT",
        baseUrl: "https://tofunft.com",
        collectionPath: "",
        itemPath: "/nft/avax/{addr}/{id}",
      },
    ],
  },
  [InnerChainUniqueId.BASE]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.BASE,
    logo: require("@/assets/images/chains/base.webp"),
    chainId: "8453",
    chainName: "Base",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
      icon: require("@/assets/images/tokens/eth_token.webp"),
    },
    rpcList: [
      "https://developer-access-mainnet.base.org",
      "https://mainnet.base.org",
    ],
    blockscoutApiList: [
      "https://basescan.org/api",
      "https://base.blockscout.com/api",
    ],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://basescan.org",
      [ExplorerLanguages.ZH]: "https://basescan.org",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/token/{token}?a={addr}",
    },
  },
  [InnerChainUniqueId.BOBA]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.BOBA,
    logo: require("@/assets/images/chains/boba.webp"),
    chainId: "288",
    chainName: "Boba",
    nativeCurrency: {
      name: "Ether",
      decimals: 18,
      symbol: "ETH",
      icon: require("@/assets/images/tokens/eth_token.webp"),
    },
    rpcList: [
      "https://mainnet.boba.network",
      "https://boba-mainnet.gateway.pokt.network/v1/lb/62738086ea1b320039c49415",
    ],
    blockscoutApiList: ["https://api.bobascan.com/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://blockexplorer.boba.network",
      [ExplorerLanguages.ZH]: "https://blockexplorer.boba.network",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/token/{token}?a={addr}",
    },
  },
  [InnerChainUniqueId.BITGERT]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.BITGERT,
    logo: require("@/assets/images/chains/bitgert.webp"),
    chainId: "32520",
    chainName: "Bitgert",
    nativeCurrency: {
      name: "Brise",
      decimals: 18,
      symbol: "BRISE",
    },
    rpcList: [
      "https://rpc.icecreamswap.com",
      "https://mainnet-rpc.brisescan.com",
      "https://nodes.vefinetwork.org/bitgert",
      "https://flux-rpc.brisescan.com",
      "https://flux-rpc1.brisescan.com",
      "https://flux-rpc2.brisescan.com",
    ],
    blockscoutApiList: ["https://brisescan.com/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://brisescan.com",
      [ExplorerLanguages.ZH]: "https://brisescan.com",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
  },
  [InnerChainUniqueId.CELO]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.CELO,
    logo: require("@/assets/images/chains/celo.webp"),
    chainId: "42220",
    chainName: "Celo",
    nativeCurrency: {
      name: "CELO",
      symbol: "CELO",
      decimals: 18,
    },
    rpcList: [
      "https://forno.celo.org",
      "https://rpc.ankr.com/celo",
      "https://celo-mainnet.infura.io/v3/6b851498cebb4893b436e986cf1f5458",
      "https://1rpc.io/celo",
    ],
    blockscoutApiList: ["https://explorer.celo.org/mainnet/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://explorer.celo.org/mainnet/",
      [ExplorerLanguages.ZH]: "https://explorer.celo.org/mainnet/",
    },
    explorerPaths: {
      tx: "tx/{txid}",
      address: "address/{addr}",
      token: "address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
  },
  [InnerChainUniqueId.CONFLUX]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.CONFLUX,
    logo: require("@/assets/images/chains/conflux.webp"),
    chainId: "1030",
    chainName: "Conflux eSpace",
    nativeCurrency: {
      name: "CFX",
      symbol: "CFX",
      decimals: 18,
    },
    rpcList: ["https://evm.confluxrpc.com"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://evm.confluxscan.net",
      [ExplorerLanguages.ZH]: "https://evm.confluxscan.net",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/token/{token}?from={addr}&to={addr}",
    },
  },
  [InnerChainUniqueId.CRO]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.CRO,
    logo: require("@/assets/images/chains/cronos.webp"),
    chainId: "25",
    chainName: "Cronos",
    nativeCurrency: {
      name: "Cronos",
      symbol: "CRO",
      decimals: 18,
    },
    rpcList: [
      "https://evm.cronos.org",
      "https://evm-cronos.crypto.org",
      "https://cronos-evm.publicnode.com",
      "https://cronos.blockpi.network/v1/rpc/public",
      "https://node.croswap.com/rpc",
    ],
    blockscoutApiList: [
      "https://cronos.org/explorer/api",
      "https://explorer.celo.org/mainnet/api",
    ],
    nft: {
      supportResync: true,
    },
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://cronoscan.com/",
      [ExplorerLanguages.ZH]: "https://cronoscan.com/",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/token/{token}?a={addr}",
    },
  },
  [InnerChainUniqueId.CUBE]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.CUBE,
    logo: require("@/assets/images/chains/cube.webp"),
    chainId: "1818",
    chainName: "CUBE Chain",
    nativeCurrency: {
      name: "CUBE",
      symbol: "CUBE",
      decimals: 18,
    },
    rpcList: [
      "https://http-mainnet.cube.network",
      "https://http-mainnet-sg.cube.network",
    ],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://cubescan.network",
      [ExplorerLanguages.ZH]: "https://cubescan.network",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/token/{token}?tab=Transfers&a={addr}",
    },
  },
  [InnerChainUniqueId.CMP]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.CMP,
    logo: require("@/assets/images/chains/cmp.webp"),
    chainId: "256256",
    chainName: "Caduceus",
    nativeCurrency: {
      name: "CMP",
      symbol: "CMP",
      decimals: 18,
    },
    rpcList: ["https://mainnet.block.caduceus.foundation"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://mainnet.scan.caduceus.foundation",
      [ExplorerLanguages.ZH]: "https://mainnet.scan.caduceus.foundation",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/token/{token}?a={addr}",
    },
  },
  [InnerChainUniqueId.ENULS]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.ENULS,
    logo: require("@/assets/images/chains/enuls.webp"),
    chainId: "119",
    chainName: "ENULS",
    nativeCurrency: {
      name: "NULS",
      symbol: "NULS",
      decimals: 18,
      icon: require("@/assets/images/tokens/enuls_token.webp"),
    },
    rpcList: ["https://evmapi.nuls.io", "https://evmapi2.nuls.io"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://evmscan.nuls.io/",
      [ExplorerLanguages.ZH]: "https://evmscan.nuls.io/",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
  },
  [InnerChainUniqueId.EOS_EVM]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.EOS_EVM,
    logo: require("@/assets/images/chains/eos.webp"),
    chainId: "17777",
    chainName: "EOS EVM",
    nativeCurrency: { name: "EOS", symbol: "EOS", decimals: 18 },
    rpcList: ["https://api.evm.eosnetwork.com/"],
    blockscoutApiList: ["https://explorer.evm.eosnetwork.com/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://explorer.evm.eosnetwork.com/",
      [ExplorerLanguages.ZH]: "https://explorer.evm.eosnetwork.com/",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
  },
  [InnerChainUniqueId.EVMOS]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.EVMOS,
    logo: require("@/assets/images/chains/evmos.webp"),
    chainId: "9001",
    chainName: "Evmos",
    nativeCurrency: {
      name: "Evmos",
      symbol: "EVMOS",
      decimals: 18,
    },
    rpcList: [
      "https://eth.bd.evmos.org:8545",
      "https://evmos-mainnet.public.blastapi.io",
      "https://evmos-evm.publicnode.com",
    ],
    blockscoutApiList: ["https://blockscout.evmos.org/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://escan.live/",
      [ExplorerLanguages.ZH]: "https://escan.live/",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/token/{token}?a={addr}",
    },
  },
  [InnerChainUniqueId.FANTOM]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.FANTOM,
    logo: require("@/assets/images/chains/fantom.webp"),
    chainId: "250",
    chainName: "Fantom",
    nativeCurrency: {
      name: "Fantom",
      symbol: "FTM",
      decimals: 18,
    },
    rpcList: [
      "https://rpc.ftm.tools",
      "https://rpcapi.fantom.network",
      "https://rpc.fantom.network",
      "https://rpc.ankr.com/fantom",
      "https://fantom.publicnode.com",
    ],
    blockscoutApiList: ["https://api.ftmscan.com/api"],
    nft: {
      supportResync: true,
    },
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://ftmscan.com",
      [ExplorerLanguages.ZH]: "https://ftmscan.com",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/token/{token}?a={addr}",
    },
    nftMarkets: [
      {
        name: "Artion",
        baseUrl: "https://artion.io",
        collectionPath: "/explore?collections={addr}",
        itemPath: "/explore/{addr}/{id}",
      },
    ],
  },
  [InnerChainUniqueId.FILECOIN_EVM]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.FILECOIN_EVM,
    logo: require("@/assets/images/chains/fil.webp"),
    chainId: "314",
    chainName: "Filecoin EVM",
    nativeCurrency: {
      name: "Filecoin",
      decimals: 18,
      symbol: "FIL",
    },
    rpcList: [
      "https://api.node.glif.io/rpc/v1",
      "https://fil-rpc.foxnb.net/rpc/v1",
      "https://rpc.ankr.com/filecoin",
      "https://filfox.info/rpc/v1",
    ],
    filfoxApiList: ["https://filfox.info/api/v1"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://filfox.info/en/",
      [ExplorerLanguages.ZH]: "https://filfox.info/zh/",
    },
    explorerPaths: {
      tx: "message/{txid}",
      address: "address/{addr}",
    },
    minGasLimits: [
      {
        gasLimit: 2280000,
      },
    ],
  },
  [InnerChainUniqueId.FLARE]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.FLARE,
    logo: require("@/assets/images/chains/flare.webp"),
    chainId: "14",
    chainName: "Flare",
    nativeCurrency: {
      name: "Flare",
      symbol: "FLR",
      decimals: 18,
    },
    rpcList: ["https://flare-api.flare.network/ext/C/rpc"],
    blockscoutApiList: ["https://songbird-explorer.flare.network/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://flare-explorer.flare.network",
      [ExplorerLanguages.ZH]: "https://flare-explorer.flare.network",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
  },
  [InnerChainUniqueId.GNOSIS]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.GNOSIS,
    logo: require("@/assets/images/chains/gnosis.webp"),
    chainId: "100",
    chainName: "Gnosis Chain (xDai)",
    nativeCurrency: {
      name: "xDAI",
      symbol: "xDAI",
      decimals: 18,
    },
    rpcList: [
      "https://rpc.gnosischain.com",
      "https://xdai.mytokenpocket.vip",
      "https://xdai.poanetwork.dev",
      "https://dai.poa.network",
      "https://rpc.ankr.com/gnosis",
      "https://gnosis.blockpi.network/v1/rpc/public",
    ],
    blockscoutApiList: ["https://blockscout.com/xdai/mainnet/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://blockscout.com/xdai/mainnet/",
      [ExplorerLanguages.ZH]: "https://blockscout.com/xdai/mainnet/",
    },
    explorerPaths: {
      tx: "tx/{txid}",
      address: "address/{addr}",
      token: "address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
  },
  [InnerChainUniqueId.GODWOKEN]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.GODWOKEN,
    logo: require("@/assets/images/chains/godwoken.webp"),
    chainId: "71402",
    chainName: "Godwoken V1",
    nativeCurrency: {
      name: "pCKB",
      symbol: "pCKB",
      decimals: 18,
    },
    rpcList: ["https://v1.mainnet.godwoken.io/rpc"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://v1.gwscan.com/",
      [ExplorerLanguages.ZH]: "https://v1.gwscan.com/zh-CN/",
    },
    explorerPaths: {
      tx: "tx/{txid}",
      address: "address/{addr}",
    },
  },
  [InnerChainUniqueId.HECO]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.HECO,
    logo: require("@/assets/images/chains/heco.webp"),
    chainId: "128",
    chainName: "Huobi ECO Chain",
    nativeCurrency: {
      name: "Huobi ECO Chain Native Token",
      symbol: "HT",
      decimals: 18,
    },
    rpcList: [
      "https://http-mainnet.hecochain.com",
      "https://http-mainnet-node.defibox.com",
    ],
    blockscoutApiList: ["https://api.hecoinfo.com/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://hecoinfo.com",
      [ExplorerLanguages.ZH]: "https://hecoinfo.com",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/token/{token}?a={addr}&tab=Transfers",
    },
  },
  [InnerChainUniqueId.KAVA]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.KAVA,
    logo: require("@/assets/images/chains/kava.webp"),
    chainId: "2222",
    chainName: "Kava EVM Co-Chain",
    nativeCurrency: {
      name: "KAVA",
      symbol: "KAVA",
      decimals: 18,
    },
    rpcList: ["https://evm.kava.io", "https://evm2.kava.io"],
    blockscoutApiList: ["https://explorer.kava.io/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://explorer.kava.io",
      [ExplorerLanguages.ZH]: "https://explorer.kava.io",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
  },
  [InnerChainUniqueId.KCC]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.KCC,
    logo: require("@/assets/images/chains/kcc.webp"),
    chainId: "321",
    chainName: "KCC",
    nativeCurrency: {
      name: "KuCoin Token",
      symbol: "KCS",
      decimals: 18,
    },
    rpcList: [
      "https://rpc-mainnet.kcc.network",
      "https://kcc.mytokenpocket.vip",
    ],
    blockscoutApiList: ["https://scan.kcc.io/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://scan.kcc.io/",
      [ExplorerLanguages.ZH]: "https://scan.kcc.io/",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
  },
  [InnerChainUniqueId.KLAY]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.KLAY,
    logo: require("@/assets/images/chains/klay.webp"),
    chainId: "8217",
    chainName: "Klaytn",
    nativeCurrency: {
      name: "Klaytn",
      symbol: "KLAY",
      decimals: 18,
    },
    rpcList: [
      "https://public-node-api.klaytnapi.com/v1/cypress",
      "https://cypress.fautor.app/archive",
      "https://klaytn.mytokenpocket.vip",
      "https://klaytn01.fandom.finance",
      "https://klaytn02.fandom.finance",
      "https://klaytn03.fandom.finance",
      "https://klaytn04.fandom.finance",
      "https://klaytn05.fandom.finance",
      "https://cypress.fandom.finance/archive",
    ],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://scope.klaytn.com",
      [ExplorerLanguages.ZH]: "https://scope.klaytn.com",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/token/{token}?tabId=tokenTransfer&account={addr}&token={token}",
    },
    nftMarkets: [
      {
        name: "OpenSea",
        baseUrl: "https://opensea.io",
        collectionPath: "/assets/klaytn/{addr}",
        itemPath: "/assets/klaytn/{addr}/{id}",
      },
    ],
  },
  [InnerChainUniqueId.LINEA]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.LINEA,
    logo: require("@/assets/images/chains/linea.webp"),
    chainId: "59144",
    chainName: "Linea",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
      icon: require("@/assets/images/tokens/eth_token.webp"),
    },
    rpcList: [
      "https://linea-mainnet.infura.io/v3/d039103314584a379e33c21fbe89b6cb",
      "https://linea-mainnet.infura.io/v3/9d60b7d314be4567adf4530f4b9dd801",
      "https://linea-mainnet.infura.io/v3/6b851498cebb4893b436e986cf1f5458",
    ],
    blockscoutApiList: ["https://explorer.linea.build/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://explorer.linea.build",
      [ExplorerLanguages.ZH]: "https://explorer.linea.build",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
  },
  [InnerChainUniqueId.MANTLE]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.MANTLE,
    logo: require("@/assets/images/chains/mantle.webp"),
    chainId: "5000",
    chainName: "Mantle",
    nativeCurrency: {
      name: "MNT",
      symbol: "MNT",
      decimals: 18,
    },
    rpcList: [
      "https://rpc.mantle.xyz/",
      "https://mantle.public-rpc.com/",
      "https://blastapi.io/public-api/mantle",
      "https://mantle.publicnode.com/",
    ],
    blockscoutApiList: ["https://explorer.mantle.xyz/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://explorer.mantle.xyz",
      [ExplorerLanguages.ZH]: "https://explorer.mantle.xyz",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
  },
  [InnerChainUniqueId.METIS]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.METIS,
    logo: require("@/assets/images/chains/metis.webp"),
    chainId: "1088",
    chainName: "Metis Andromeda",
    nativeCurrency: {
      name: "METIS",
      symbol: "METIS",
      decimals: 18,
    },
    rpcList: ["https://andromeda.metis.io/?owner=1088"],
    blockscoutApiList: ["https://andromeda-explorer.metis.io/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://andromeda-explorer.metis.io",
      [ExplorerLanguages.ZH]: "https://andromeda-explorer.metis.io",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
  },
  [InnerChainUniqueId.MOONBEAM]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.MOONBEAM,
    logo: require("@/assets/images/chains/moonbeam.webp"),
    chainId: "1284",
    chainName: "Moonbeam",
    nativeCurrency: {
      name: "Glimmer",
      symbol: "GLMR",
      decimals: 18,
    },
    rpcList: [
      "https://rpc.api.moonbeam.network",
      "https://rpc.ankr.com/moonbeam",
    ],
    blockscoutApiList: ["https://blockscout.moonbeam.network/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://moonscan.io",
      [ExplorerLanguages.ZH]: "https://moonscan.io",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/token/{token}?a={addr}",
    },
  },
  [InnerChainUniqueId.MOONRIVER]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.MOONRIVER,
    logo: require("@/assets/images/chains/moonriver.webp"),
    chainId: "1285",
    chainName: "Moonriver",
    nativeCurrency: {
      name: "Moonriver",
      symbol: "MOVR",
      decimals: 18,
    },
    rpcList: ["https://rpc.api.moonriver.moonbeam.network"],
    blockscoutApiList: ["https://blockscout.moonriver.moonbeam.network/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://moonriver.moonscan.io",
      [ExplorerLanguages.ZH]: "https://moonriver.moonscan.io",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/token/{token}?a={addr}",
    },
  },
  [InnerChainUniqueId.OKX]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.OKX,
    logo: require("@/assets/images/chains/okx.webp"),
    chainId: "66",
    chainName: "OKC",
    nativeCurrency: {
      name: "OKXChain Token",
      symbol: "OKT",
      decimals: 18,
    },
    rpcList: [
      "https://exchainrpc.okex.org",
      "https://okchain.mytokenpocket.vip",
    ],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://www.oklink.com/en/okc/",
      [ExplorerLanguages.ZH]: "https://www.oklink.com/zh-cn/okc/",
    },
    explorerPaths: {
      tx: "tx/{txid}",
      address: "address/{addr}",
    },
  },
  [InnerChainUniqueId.OPBNB]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.OPBNB,
    logo: require("@/assets/images/chains/bnb.webp"),
    chainId: "204",
    chainName: "opBNB Mainnet",
    nativeCurrency: {
      name: "BNB",
      symbol: "BNB",
      decimals: 18,
    },
    rpcList: [
      "https://opbnb-mainnet-rpc.bnbchain.org",
      "https://opbnb-mainnet.nodereal.io/v1/64a9df0874fb4a93b9d0a3849de012d3",
      "https://opbnb-mainnet.nodereal.io/v1/e9a36765eb8a40b9bd12e680a1fd2bc5",
    ],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://mainnet.opbnbscan.com/",
      [ExplorerLanguages.ZH]: "https://mainnet.opbnbscan.com/",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/token/{token}?a={addr}",
    },
  },
  [InnerChainUniqueId.OPTIMISM]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.OPTIMISM,
    logo: require("@/assets/images/chains/optimism.webp"),
    chainId: "10",
    chainName: "Optimism",
    nativeCurrency: {
      name: "Ether",
      symbol: "OETH",
      decimals: 18,
      icon: require("@/assets/images/tokens/eth_token.webp"),
    },
    rpcList: [
      "https://mainnet.optimism.io",
      "https://opt-mainnet.g.alchemy.com/v2/qxNJBwPVBNND7pN2BBqdaBv9n8DhKRRK",
      "https://optimism-mainnet.s.chainbase.online/v1/2GZosQJonXa2yN7GBfv9BCi26Jj", // from imtoken
      "https://endpoints.omniatech.io/v1/op/mainnet/public",
      "https://rpc.ankr.com/optimism",
      "https://1rpc.io/op",
    ],
    blockscoutApiList: [
      "https://api-optimistic.etherscan.io/api",
      "https://blockscout.com/optimism/mainnet/api",
    ],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://optimistic.etherscan.io",
      [ExplorerLanguages.ZH]: "https://optimistic.etherscan.io",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/token/{token}?a={addr}",
    },
    nftMarkets: [
      {
        name: "OpenSea",
        baseUrl: "https://opensea.io",
        collectionPath: "/assets/optimism/{addr}",
        itemPath: "/assets/optimism/{addr}/{id}",
      },
    ],
    minGasLimits: [
      {
        functionHash: "0xa9059cbb", // transfer
        gasLimit: 52000,
      },
    ],
  },
  [InnerChainUniqueId.PGN]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.PGN,
    logo: require("@/assets/images/chains/pgn.webp"),
    chainId: "424",
    chainName: "PGN",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
    },
    rpcList: ["https://rpc.publicgoods.network"],
    blockscoutApiList: ["https://explorer.publicgoods.network/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://explorer.publicgoods.network/",
      [ExplorerLanguages.ZH]: "https://explorer.publicgoods.network/",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
  },
  [InnerChainUniqueId.POLYGON]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.POLYGON,
    logo: require("@/assets/images/chains/polygon.webp"),
    chainId: "137",
    chainName: "Polygon",
    nativeCurrency: {
      name: "MATIC",
      symbol: "MATIC",
      decimals: 18,
    },
    rpcList: [
      "https://rpc-mainnet.maticvigil.com",
      "https://rpc-mainnet.matic.network",
      "https://polygon-mainnet.g.alchemy.com/v2/w0Y6amBEt_0IZIA0os2PObS-qTMTn5LB",
      "https://polygon-mainnet.infura.io/v3/6b851498cebb4893b436e986cf1f5458",
      "https://polygon-mainnet.chainstacklabs.com",
      "https://rpc-mainnet.matic.quiknode.pro",
      "https://matic-mainnet-full-rpc.bwarelabs.com",
      "https://rpc.ankr.com/polygon",
      "https://polygon-mainnet.blastapi.io/1279251a-ca2d-4491-bb80-849a5b0c77fe",
    ],
    blockscoutApiList: ["https://api.polygonscan.com/api"],
    nft: {
      supportResync: true,
    },
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://polygonscan.com",
      [ExplorerLanguages.ZH]: "https://polygonscan.com",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/token/{token}?a={addr}",
    },
    nftMarkets: [
      {
        name: "OpenSea",
        baseUrl: "https://opensea.io",
        collectionPath: "/assets/matic/{addr}",
        itemPath: "/assets/matic/{addr}/{id}",
      },
      {
        name: "tofuNFT",
        baseUrl: "https://tofunft.com",
        collectionPath: "",
        itemPath: "/nft/polygon/{addr}/{id}",
      },
      {
        name: "Element",
        baseUrl: "https://element.market",
        collectionPath: "/assets/polygon/{addr}",
        itemPath: "/assets/polygon/{addr}/{id}",
      },
    ],
    minMaxPriorityFeePerGas: "30000000000",
    minGasLimits: [
      {
        functionHash: "0xa9059cbb", // transfer
        gasLimit: 52000,
      },
    ],
  },
  [InnerChainUniqueId.POLYGON_ZKEVM]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.POLYGON_ZKEVM,
    logo: require("@/assets/images/chains/polygon.webp"),
    chainId: "1101",
    chainName: "Polygon zkEVM",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
      icon: require("@/assets/images/tokens/eth_token.webp"),
    },
    rpcList: ["https://zkevm-rpc.com"],
    blockscoutApiList: ["https://api-zkevm.polygonscan.com/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://zkevm.polygonscan.com/",
      [ExplorerLanguages.ZH]: "https://zkevm.polygonscan.com/",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/token/{token}?a={addr}",
    },
  },
  [InnerChainUniqueId.REI]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.REI,
    logo: require("@/assets/images/chains/rei.webp"),
    chainId: "47805",
    chainName: "REI Network",
    nativeCurrency: { name: "REI", symbol: "REI", decimals: 18 },
    rpcList: ["https://rpc.rei.network"],
    blockscoutApiList: ["https://scan.rei.network/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://scan.rei.network",
      [ExplorerLanguages.ZH]: "https://scan.rei.network",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
  },
  [InnerChainUniqueId.SYS]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.SYS,
    logo: require("@/assets/images/chains/sys.webp"),
    chainId: "57",
    chainName: "Syscoin NEVM",
    nativeCurrency: {
      name: "SYS",
      symbol: "SYS",
      decimals: 18,
    },
    rpcList: ["https://rpc.syscoin.org", "https://rpc.ankr.com/syscoin"],
    blockscoutApiList: ["https://explorer.syscoin.org/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://explorer.syscoin.org",
      [ExplorerLanguages.ZH]: "https://explorer.syscoin.org",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
  },
  [InnerChainUniqueId.ZKSYNC_ERA]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.ZKSYNC_ERA,
    logo: require("@/assets/images/chains/zksync.webp"),
    chainId: "324",
    chainName: "zkSync Era",
    nativeCurrency: {
      name: "zkSync Ether",
      decimals: 18,
      symbol: "ETH",
      icon: require("@/assets/images/tokens/eth_token.webp"),
    },
    rpcList: ["https://zksync2-mainnet.zksync.io"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://explorer.zksync.io/",
      [ExplorerLanguages.ZH]: "https://explorer.zksync.io/",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
    },
    blockscoutApiList: ["https://zksync2-mainnet.zkscan.io/api"],
    nftMarkets: [
      {
        name: "Apescan",
        baseUrl: "https://apescan.co/",
        itemPath: "/#/NftOverview?id={id}&address={addr}",
        collectionPath: "/#/nfts?address={addr}",
      },
      {
        name: "Element",
        baseUrl: "https://element.market",
        itemPath: "/assets/zksync/{addr}/{id}",
        collectionPath: "/assets/zksync/{addr}",
      },
    ],
    nft: {
      supportResync: false,
    },
    minGasLimits: [
      {
        functionHash: "0xa9059cbb", // transfer
        gasLimit: 52000,
      },
    ],
  },
  [InnerChainUniqueId.ZENITH]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.ZENITH,
    logo: require("@/assets/images/chains/zenith.webp"),
    chainId: "79",
    chainName: "Zenith",
    nativeCurrency: {
      name: "ZENITH",
      symbol: "ZENITH",
      decimals: 18,
    },
    rpcList: [
      "https://dataserver-1.zenithchain.co",
      "https://dataserver-us-1.zenithchain.co",
      "https://dataserver-asia-1.zenithchain.co",
    ],
    blockscoutApiList: ["https://scan.zenithchain.co/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://scan.zenithchain.co",
      [ExplorerLanguages.ZH]: "https://scan.zenithchain.co",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
  },
  [InnerChainUniqueId.GOERLI]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.GOERLI,
    logo: require("@/assets/images/chains/placeholder.webp"),
    chainId: "5",
    chainName: "Goerli Testnet",
    nativeCurrency: {
      name: "Goerli Ether",
      decimals: 18,
      symbol: "GETH",
    },
    rpcList: [
      "https://goerli.infura.io/v3/d039103314584a379e33c21fbe89b6cb",
      "https://rpc.goerli.mudit.blog/",
      "https://rpc.ankr.com/eth_goerli",
      "https://goerli.infura.io/v3/6b851498cebb4893b436e986cf1f5458",
      "https://goerli.blockpi.network/v1/rpc/public",
    ],
    blockscoutApiList: ["https://eth-goerli.blockscout.com/api"],
    nft: {
      supportResync: true,
    },
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://goerli.etherscan.io",
      [ExplorerLanguages.ZH]: "https://goerli.etherscan.io",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/token/{token}?a={addr}",
    },
    testnet: true,
    faucetWebList: [
      "https://faucet.quicknode.com/ethereum/goerli",
      "https://goerlifaucet.com/",
      "https://goerli-faucet.pk910.de/",
    ],
  },
  [InnerChainUniqueId.AVAX_FUJI]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.AVAX_FUJI,
    logo: require("@/assets/images/chains/avax_test.webp"),
    chainId: "43113",
    chainName: "AVAX Fuji Testnet",
    nativeCurrency: {
      name: "AVAX",
      symbol: "AVAX",
      decimals: 18,
    },
    rpcList: ["https://api.avax-test.network/ext/bc/C/rpc"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://testnet.snowtrace.io/",
      [ExplorerLanguages.ZH]: "https://testnet.snowtrace.io/",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/token/{token}?a={addr}",
    },
    testnet: true,
    faucetWebList: ["https://faucet.avax.network/"],
  },
  [InnerChainUniqueId.BASE_GOERLI]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.BASE_GOERLI,
    logo: require("@/assets/images/chains/base_test.webp"),
    chainId: "84531",
    chainName: "Base Goerli Testnet",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
      icon: require("@/assets/images/tokens/eth_test_token.webp"),
    },
    rpcList: [
      "https://goerli.base.org",
      "https://base-goerli.blastapi.io/1279251a-ca2d-4491-bb80-849a5b0c77fe",
    ],
    blockscoutApiList: [
      "https://goerli.basescan.org/api",
      "https://base-goerli.blockscout.com/api",
    ],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://goerli.basescan.org",
      [ExplorerLanguages.ZH]: "https://goerli.basescan.org",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/token/{token}?a={addr}",
    },
    testnet: true,
    faucetWebList: ["https://faucet.triangleplatform.com/base/goerli"],
  },
  [InnerChainUniqueId.GOSHEN_TEST]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.GOSHEN_TEST,
    logo: require("@/assets/images/chains/goshen.webp"),
    chainId: "21772",
    chainName: "Goshen Test Alpha",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
      icon: require("@/assets/images/tokens/eth_test_token.webp"),
    },
    rpcList: ["https://testnet-alpha.goshen.network/rpc/"],
    blockscoutApiList: ["https://explorer-testnet.goshen.network/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://explorer-testnet.goshen.network/",
      [ExplorerLanguages.ZH]: "https://explorer-testnet.goshen.network/",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
    testnet: true,
  },
  [InnerChainUniqueId.LINEA_TEST]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.LINEA_TEST,
    logo: require("@/assets/images/chains/linea.webp"),
    chainId: "59140",
    chainName: "Linea Testnet",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
      icon: require("@/assets/images/tokens/eth_test_token.webp"),
    },
    rpcList: ["https://rpc.goerli.linea.build/"],
    blockscoutApiList: ["https://explorer.goerli.linea.build/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://explorer.goerli.linea.build/",
      [ExplorerLanguages.ZH]: "https://explorer.goerli.linea.build/",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
    testnet: true,
  },
  [InnerChainUniqueId.MANTA_TEST]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.MANTA_TEST,
    logo: require("@/assets/images/chains/manta.webp"),
    chainId: "3441005",
    chainName: "Manta Testnet",
    nativeCurrency: {
      name: "MANTA",
      symbol: "MANTA",
      decimals: 18,
    },
    rpcList: ["https://manta-testnet.calderachain.xyz/http"],
    blockscoutApiList: ["https://manta-testnet.calderaexplorer.xyz/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://manta-testnet.calderaexplorer.xyz/",
      [ExplorerLanguages.ZH]: "https://manta-testnet.calderaexplorer.xyz/",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
    testnet: true,
  },
  [InnerChainUniqueId.OPSIDE_TESTNET_PRE_ALPHA]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.OPSIDE_TESTNET_PRE_ALPHA,
    logo: require("@/assets/images/chains/opside_test.webp"),
    chainId: "51178",
    chainName: "Opside Testnet Pre-Alpha",
    nativeCurrency: {
      name: "IDE",
      symbol: "IDE",
      decimals: 18,
    },
    rpcList: [
      "https://pre-alpha-hk-http-geth.opside.network",
      "https://pre-alpha-us-http-geth.opside.networ",
    ],
    blockscoutApiList: ["https://pre-alpha.opside.info/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://pre-alpha.opside.info/",
      [ExplorerLanguages.ZH]: "https://pre-alpha.opside.info/",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
    testnet: true,
    faucetWebList: [
      "https://docs.opside.network/user-guide/get-some-test-tokens-through-faucet",
    ],
  },
  [InnerChainUniqueId.POLYGON_ZKEVM_TEST]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.POLYGON_ZKEVM_TEST,
    logo: require("@/assets/images/chains/polygon_test.webp"),
    chainId: "1442",
    chainName: "Polygon zkEVM Testnet",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
      icon: require("@/assets/images/tokens/eth_test_token.webp"),
    },
    rpcList: ["https://rpc.public.zkevm-test.net"],
    blockscoutApiList: ["https://explorer.public.zkevm-test.net/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://explorer.public.zkevm-test.net",
      [ExplorerLanguages.ZH]: "https://explorer.public.zkevm-test.net",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
    testnet: true,
  },
  [InnerChainUniqueId.SCROLL_ALPHA]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.SCROLL_ALPHA,
    logo: require("@/assets/images/chains/scroll_test.webp"),
    chainId: "534353",
    chainName: "Scroll Alpha Testnet",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
      icon: require("@/assets/images/tokens/eth_test_token.webp"),
    },
    rpcList: ["https://alpha-rpc.scroll.io/l2"],
    blockscoutApiList: ["https://blockscout.scroll.io/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://blockscout.scroll.io/",
      [ExplorerLanguages.ZH]: "https://blockscout.scroll.io/",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
    testnet: true,
  },
  [InnerChainUniqueId.SEPOLIA]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.SEPOLIA,
    logo: require("@/assets/images/chains/placeholder.webp"),
    chainId: "11155111",
    chainName: "Sepolia Testnet",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
      icon: require("@/assets/images/tokens/eth_test_token.webp"),
    },
    rpcList: [
      "https://rpc.sepolia.org",
      "https://eth-sepolia.public.blastapi.io",
      "https://ethereum-sepolia.blockpi.network/v1/rpc/public",
      "https://rpc-sepolia.rockx.com",
      "https://rpc2.sepolia.org",
    ],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://sepolia.etherscan.io/",
      [ExplorerLanguages.ZH]: "https://sepolia.etherscan.io/",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/token/{token}?a={addr}",
    },
    nft: {
      supportResync: true,
    },
    testnet: true,
    faucetWebList: [
      "https://faucet.quicknode.com/ethereum/sepolia",
      "https://www.infura.io/faucet",
      "https://faucet-sepolia.rockx.com/",
      "https://sepoliafaucet.com/",
      "https://sepolia-faucet.pk910.de",
    ],
  },
  [InnerChainUniqueId.SHARDEUM_SPHINX_1]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.SHARDEUM_SPHINX_1,
    logo: require("@/assets/images/chains/shardeum_test.webp"),
    chainId: "8082",
    chainName: "Shardeum Sphinx Validator 1.X",
    nativeCurrency: {
      name: "SHM",
      symbol: "SHM",
      decimals: 18,
    },
    rpcList: ["https://sphinx.shardeum.org/"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://explorer-sphinx.shardeum.org/",
      [ExplorerLanguages.ZH]: "https://explorer-sphinx.shardeum.org/",
    },
    explorerPaths: {
      tx: "/transaction/{txid}",
      address: "/account/{addr}",
    },
    testnet: true,
    faucetWebList: [
      "https://faucet-sphinx.shardeum.org/",
      "https://chaindrop.org/?chainid=8082&token=0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      "https://get-shm.online/",
    ],
  },
  [InnerChainUniqueId.SHARDEUM_SPHINX_DAPP_1]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.SHARDEUM_SPHINX_DAPP_1,
    logo: require("@/assets/images/chains/shardeum_test.webp"),
    chainId: "8081",
    chainName: "Shardeum Sphinx Dapp 1.X",
    nativeCurrency: {
      name: "SHM",
      symbol: "SHM",
      decimals: 18,
    },
    rpcList: ["https://dapps.shardeum.org"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://explorer-dapps.shardeum.org",
      [ExplorerLanguages.ZH]: "https://explorer-dapps.shardeum.org",
    },
    explorerPaths: {
      tx: "/transaction/{txid}",
      address: "/account/{addr}",
    },
    testnet: true,
    faucetWebList: ["https://faucet-dapps.shardeum.org/"],
  },
  [InnerChainUniqueId.TAIKO_ALPHA_3]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.TAIKO_ALPHA_3,
    logo: require("@/assets/images/chains/taiko_test.webp"),
    chainId: "167005",
    chainName: "Taiko Grimsvotn L2",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
    },
    rpcList: ["https://rpc.test.taiko.xyz"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://explorer.test.taiko.xyz/",
      [ExplorerLanguages.ZH]: "https://explorer.test.taiko.xyz/",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
    blockscoutApiList: ["https://explorer.test.taiko.xyz/api"],
    testnet: true,
    faucetWebList: ["https://bridge.test.taiko.xyz/#/faucet"],
  },
  [InnerChainUniqueId.TAIKO_ELDFELL]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.TAIKO_ELDFELL,
    logo: require("@/assets/images/chains/taiko_test.webp"),
    chainId: "167006",
    chainName: "Taiko Eldfell L3",
    nativeCurrency: {
      name: "ETH",
      symbol: "ETH",
      decimals: 18,
    },
    rpcList: ["https://rpc.l3test.taiko.xyz"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://explorer.l3test.taiko.xyz",
      [ExplorerLanguages.ZH]: "https://explorer.l3test.taiko.xyz",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
      token: "/address/{addr}/tokens/{token}/token-transfers#address-tabs",
    },
    blockscoutApiList: ["https://explorer.l3test.taiko.xyz/api"],
    testnet: true,
  },
  [InnerChainUniqueId.ZETA_ATHENS_2]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.ZETA_ATHENS_2,
    logo: require("@/assets/images/chains/zeta_test.webp"),
    chainId: "7001",
    chainName: "ZetaChain Athens 2",
    nativeCurrency: {
      name: "ZETA",
      symbol: "ZETA",
      decimals: 18,
    },
    rpcList: ["https://api.athens2.zetachain.com/evm"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://explorer.zetachain.com/",
      [ExplorerLanguages.ZH]: "https://explorer.zetachain.com/",
    },
    explorerPaths: {
      tx: "evm/tx/{txid}",
      address: "/address/{addr}",
    },
    testnet: true,
  },
  [InnerChainUniqueId.ZKSYNC_V2_TEST]: {
    coinType: CoinType.ETH,
    uniqueId: InnerChainUniqueId.ZKSYNC_V2_TEST,
    logo: require("@/assets/images/chains/zksync_test.webp"),
    chainId: "280",
    chainName: "zkSync Era Testnet",
    nativeCurrency: {
      name: "zkSync Ether",
      decimals: 18,
      symbol: "ETH",
      icon: require("@/assets/images/tokens/eth_test_token.webp"),
    },
    rpcList: ["https://zksync2-testnet.zksync.dev"],
    blockscoutApiList: ["https://zksync2-testnet.zkscan.io/api"],
    explorerUrls: {
      [ExplorerLanguages.EN]: "https://zksync2-testnet.zkscan.io/",
      [ExplorerLanguages.ZH]: "https://zksync2-testnet.zkscan.io/",
    },
    explorerPaths: {
      tx: "/tx/{txid}",
      address: "/address/{addr}",
    },
    testnet: true,
    faucetWebList: ["https://faucet.zkape.io"],
  },
};
